```{r, load libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(data.table)
library(RColorBrewer)
library(MetBrewer)
library(plotly)
```
```{r}
setwd("/Users/lindsey/Desktop/Hodges_Lab/ATAC-me\ NPCdiff/NPCDiff_ATACme/New_timepoints/data")

dyn_modC_8dayA<- read_tsv("6l_seq/dynamic_8day_A_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "cluster", "peakID")) %>% mutate(p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )
dyn_modC_8dayB<- read_tsv("6l_seq/dynamic_8day_B_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "cluster", "peakID")) %>% mutate(p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )   

dyn_modC_4dayA<- read_tsv("6l_seq/dynamic_4day_A_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "cluster", "peakID")) %>% mutate(p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )
dyn_modC_4dayB<- read_tsv("6l_seq/dynamic_4day_B_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "cluster", "peakID")) %>% mutate(p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )

dyn_modC_0dayA<- read_tsv("6l_seq/dynamic_0hr_A_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "cluster", "peakID")) %>% mutate(p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )
dyn_modC_0dayB<- read_tsv("6l_seq/dynamic_0hr_B_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "cluster", "peakID")) %>% mutate(p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )

setwd("/Users/lindsey/Desktop/Hodges_Lab/ATAC-me\ NPCdiff/NPCDiff_ATACme/New_timepoints/data")

stat_modC_8dayA<- read_tsv("6l_seq/static_8day_A_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "peakID")) %>% mutate(cluster = "static", p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )
stat_modC_8dayB<- read_tsv("6l_seq/static_8day_B_intersect.bed",col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "peakID")) %>% mutate(cluster = "static", p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )

stat_modC_4dayA<- read_tsv("6l_seq/static_4day_A_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "peakID")) %>% mutate(cluster = "static", p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )
stat_modC_4dayB<- read_tsv("6l_seq/static_4day_B_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "peakID")) %>% mutate(cluster = "static", p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = num_C/num_total) %>% filter(num_total >5 )

stat_modC_0dayA<- read_tsv("6l_seq/static_0hr_A_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "peakID")) %>% mutate(cluster = "static", p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = num_C/num_total) %>% filter(num_total >5 )
stat_modC_0dayB<- read_tsv("6l_seq/static_0hr_B_intersect.bed", col_names = c("chr", "start", "end", "strand", "num_mC", "num_hmC", "num_C", "context", "tri_context", "num_total", "region_chr", "region_start", "region_end", "peakID")) %>% mutate(cluster = "static", p_hmC = num_hmC/num_total, p_mC = num_mC/num_total, p_unmodC = (num_C)/num_total) %>% filter(num_total >5 )

dynamic_peaks<- read_tsv("TC_seq/peak_subset_dynamic.bed", col_names = c("region_chr", "region_start", "region_end", "cluster", "peakID"))
static_peaks<- read_tsv("TC_seq/peak_subset_static.bed", col_names = c("region_chr", "region_start", "region_end", "peakID")) %>% mutate("cluster" = "static") %>% select(1:3,5,4)

dyn_modC_0day<- inner_join(dyn_modC_0dayA, dyn_modC_0dayB, by= c("chr", "start", "end", "cluster", "peakID", "region_chr", "region_start", "region_end")) %>% select("chr", "start", "end", "region_chr", "region_start", "region_end","p_hmCA"="p_hmC.x", "p_mCA"="p_mC.x","p_unmodCA"="p_unmodC.x", "p_hmCB"="p_hmC.y", "p_mCB"="p_mC.y","p_unmodCB"="p_unmodC.y", "cluster", "peakID") %>% mutate(avg_phmC = (p_hmCA+p_hmCB)/2, avg_pmC = (p_mCA+p_mCB)/2, avg_punmodC = (p_unmodCA+p_unmodCB)/2)
dyn_modC_4day<- inner_join(dyn_modC_4dayA, dyn_modC_4dayB, by= c("chr", "start", "end", "cluster", "peakID", "region_chr", "region_start", "region_end")) %>% select("chr", "start", "end", "region_chr", "region_start", "region_end","p_hmCA"="p_hmC.x", "p_mCA"="p_mC.x","p_unmodCA"="p_unmodC.x", "p_hmCB"="p_hmC.y", "p_mCB"="p_mC.y","p_unmodCB"="p_unmodC.y", "cluster", "peakID") %>% mutate(avg_phmC = (p_hmCA+p_hmCB)/2, avg_pmC = (p_mCA+p_mCB)/2, avg_punmodC = (p_unmodCA+p_unmodCB)/2)
dyn_modC_8day<- inner_join(dyn_modC_8dayA, dyn_modC_8dayB, by= c("chr", "start", "end", "cluster", "peakID", "region_chr", "region_start", "region_end")) %>% select("chr", "start", "end", "region_chr", "region_start", "region_end","p_hmCA"="p_hmC.x", "p_mCA"="p_mC.x","p_unmodCA"="p_unmodC.x", "p_hmCB"="p_hmC.y", "p_mCB"="p_mC.y","p_unmodCB"="p_unmodC.y", "cluster", "peakID") %>% mutate(avg_phmC = (p_hmCA+p_hmCB)/2, avg_pmC = (p_mCA+p_mCB)/2, avg_punmodC = (p_unmodCA+p_unmodCB)/2)

stat_modC_0day <- inner_join(stat_modC_0dayA, stat_modC_0dayB, by= c("chr", "start", "end", "cluster", "peakID", "region_chr", "region_start", "region_end")) %>% select("chr", "start", "end", "region_chr", "region_start", "region_end","p_hmCA"="p_hmC.x", "p_mCA"="p_mC.x","p_unmodCA"="p_unmodC.x", "p_hmCB"="p_hmC.y", "p_mCB"="p_mC.y","p_unmodCB"="p_unmodC.y", "cluster", "peakID") %>% mutate(avg_phmC = (p_hmCA+p_hmCB)/2, avg_pmC = (p_mCA+p_mCB)/2, avg_punmodC = (p_unmodCA+p_unmodCB)/2)
stat_modC_4day <- inner_join(stat_modC_4dayA, stat_modC_4dayB, by= c("chr", "start", "end", "cluster", "peakID", "region_chr", "region_start", "region_end")) %>% select("chr", "start", "end", "region_chr", "region_start", "region_end","p_hmCA"="p_hmC.x", "p_mCA"="p_mC.x","p_unmodCA"="p_unmodC.x", "p_hmCB"="p_hmC.y", "p_mCB"="p_mC.y","p_unmodCB"="p_unmodC.y", "cluster", "peakID") %>% mutate(avg_phmC = (p_hmCA+p_hmCB)/2, avg_pmC = (p_mCA+p_mCB)/2, avg_punmodC = (p_unmodCA+p_unmodCB)/2)
stat_modC_8day <- inner_join(stat_modC_8dayA, stat_modC_8dayB, by= c("chr", "start", "end", "cluster", "peakID", "region_chr", "region_start", "region_end")) %>% select("chr", "start", "end", "region_chr", "region_start", "region_end","p_hmCA"="p_hmC.x", "p_mCA"="p_mC.x","p_unmodCA"="p_unmodC.x", "p_hmCB"="p_hmC.y", "p_mCB"="p_mC.y","p_unmodCB"="p_unmodC.y", "cluster", "peakID") %>% mutate(avg_phmC = (p_hmCA+p_hmCB)/2, avg_pmC = (p_mCA+p_mCB)/2, avg_punmodC = (p_unmodCA+p_unmodCB)/2)


peaks<- rbind(dynamic_peaks, static_peaks)
modC_0day<- rbind(stat_modC_0day, dyn_modC_0day) %>% mutate(time = "0day")
modC_4day<- rbind(stat_modC_4day, dyn_modC_4day)%>% mutate(time = "4day")
modC_8day<- rbind(stat_modC_8day, dyn_modC_8day)%>% mutate(time = "8day")

write_tsv(modC_0day, "/Users/lindsey/Desktop/Hodges_Lab/ATAC-me\ NPCdiff/NPCDiff_ATACme/New_timepoints/data/6l_seq/modC_0day_data.tsv")
write_tsv(modC_4day, "/Users/lindsey/Desktop/Hodges_Lab/ATAC-me\ NPCdiff/NPCDiff_ATACme/New_timepoints/data/6l_seq/modC_4day_data.tsv")
write_tsv(modC_8day, "/Users/lindsey/Desktop/Hodges_Lab/ATAC-me\ NPCdiff/NPCDiff_ATACme/New_timepoints/data/6l_seq/modC_8day_data.tsv")

```
```{r}
modC_0day_region<- modC_0day %>% group_by(peakID, cluster) %>% summarise(reg_mCA= mean(p_mCA), reg_hmCA = mean(p_hmCA), reg_unmodCA = mean(p_unmodCA), reg_mCB= mean(p_mCB), reg_hmCB = mean(p_hmCB), reg_unmodCB = mean(p_unmodCB)) %>% mutate(reg_avg_mC = (reg_mCA+reg_mCB)/2, reg_avg_hmC = (reg_hmCA+reg_hmCB)/2, reg_avg_unmodC = (reg_unmodCA+reg_unmodCB)/2, time = "0day")
modC_4day_region<- modC_4day %>% group_by(peakID, cluster) %>% summarise(reg_mCA= mean(p_mCA), reg_hmCA = mean(p_hmCA), reg_unmodCA = mean(p_unmodCA), reg_mCB= mean(p_mCB), reg_hmCB = mean(p_hmCB), reg_unmodCB = mean(p_unmodCB)) %>% mutate(reg_avg_mC = (reg_mCA+reg_mCB)/2, reg_avg_hmC = (reg_hmCA+reg_hmCB)/2, reg_avg_unmodC = (reg_unmodCA+reg_unmodCB)/2, time = "4day")
modC_8day_region<- modC_8day %>% group_by(peakID,cluster) %>% summarise(reg_mCA= mean(p_mCA), reg_hmCA = mean(p_hmCA), reg_unmodCA = mean(p_unmodCA), reg_mCB= mean(p_mCB), reg_hmCB = mean(p_hmCB), reg_unmodCB = mean(p_unmodCB)) %>% mutate(reg_avg_mC = (reg_mCA+reg_mCB)/2, reg_avg_hmC = (reg_hmCA+reg_hmCB)/2, reg_avg_unmodC = (reg_unmodCA+reg_unmodCB)/2, time = "8day")

modC_cluster<- rbind(modC_0day_region, modC_4day_region, modC_8day_region)
hmC_cluster<- pivot_wider(modC_cluster, id_cols = c(peakID, cluster), names_from = time, values_from = reg_avg_hmC)
mC_cluster<- pivot_wider(modC_cluster, id_cols = c(peakID, cluster), names_from = time, values_from = reg_avg_mC)

allmod_cluster<- pivot_longer(modC_cluster, names_to = "mod", values_to = "avg_signal", cols = c(reg_avg_mC, reg_avg_hmC, reg_avg_unmodC))

modC_cluster_mCsum<- group_by(modC_cluster, cluster, time) %>%summarise(mCA = mean(reg_mCA), mCB = mean(reg_mCB))
mC_boxplot<- ggplot()+
  geom_boxplot(data= modC_cluster, aes(x= time, y= reg_avg_mC, fill = cluster, color = cluster), outlier.shape = NA, alpha = 0.75)+
  geom_point(data = modC_cluster_mCsum, position = "jitter", aes(x= time, y= mCA, fill = cluster, color = cluster))+
  geom_point(data = modC_cluster_mCsum, aes(x= time, y= mCB, fill = cluster, color = cluster))+
  ylim(0, 1)+
  scale_fill_manual(values=met.brewer("Renoir", 8))+
  scale_color_manual(values=met.brewer("Renoir", 8))+
  facet_wrap(~cluster, ncol = 8)+
  theme_minimal()
mC_boxplot
```
