---
title: Heatmap for Motif Enrichment Across time
---
```{r, load libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(data.table)
library(RColorBrewer)
library(pheatmap)
```
Read in files with and without background
```{r , message = FALSE}
# (1) Get a list of files to iterate over
setwd("/Users/lindsey/Desktop/Hodges_Lab/ATAC-me NPCdiff/NPCDiff_ATACme/New_timepoints/data/HOMER/cluster")
resultFiles_noBkg = list.files(pattern="*_noBkg_knownResults.txt")
# (2) Load these in:
resultDF_noBkg = lapply(resultFiles_noBkg, readr::read_tsv, col_names = c("Motif", "Consensus", "pval", "log_pval", "qval", "target_seq#", "target_seq%", "background_seq#", "background_seq%"), skip = 1) 
# (3) Iterate over the list of filenames [1], gsubbing out the unwanted suffix, to produce a 
# List of truncated file names (e.g. "ATF3_footprint_0hr", "ATF3_footprint_12hr")
resultNames_noBkg <- lapply(resultFiles_noBkg, function(x) gsub("*_noBkg_knownResults.txt", "", x))
# (4) Rename each Tibble in the list of Tibbles [2] to something more descriptive [3]
names(resultDF_noBkg) <- resultNames_noBkg

```
```{r}
#now try plotting FC instead of P values
prepTable <- function(num){
  df <- resultDF_noBkg[[num]] %>%
  mutate(Motif2 = gsub("\\(.*", "", Motif), 
  FamilyL=str_extract(Motif, "(?<=\\().+?(?=\\))"), 
  Family = gsub(",.*$", "", FamilyL))
  
resultDF_noBkg$cluster3$Motif2 <- factor(resultDF_noBkg$cluster3$Motif2, levels= c(rev(unique(resultDF_noBkg$cluster3$Motif2))))
 t = easyr::match.factors(resultDF_noBkg$cluster3, df, by = "Motif2")
levels( resultDF_noBkg$cluster3$Motif2 )
df <- t[[2]]
df <- df %>% mutate(time = resultNames_noBkg[[num]]) %>%
    mutate(percentTargetNum = (as.numeric(gsub("%", "", `target_seq%`, fixed = TRUE))/100)) %>%
    mutate(percentBackgroundNum = (as.numeric(gsub("%", "", `background_seq%`, fixed = TRUE))/100)) %>%
    mutate(percentFold = (percentTargetNum/percentBackgroundNum)) 

df <- df %>% select("log_pval", "percentFold", "Motif2", "Family", "time")
df
}

table1 <- prepTable(1)
table1_Motif <- table1[1:25, ]
table2 <- prepTable(2)
table2_Motif <- table2[1:25, ]
table3 <- prepTable(3)
table3_Motif <- table3[1:25, ]
table4 <- prepTable(4)
table4_Motif <- table4[1:25, ]
table5 <- prepTable(5)
table5_Motif <- table5[1:25, ]
table6 <- prepTable(6)
table6_Motif <- table6[1:25, ] 
table7 <- prepTable(7)
table7_Motif <- table7[1:25, ]
table8 <- prepTable(8)
table8_Motif <- table8[1:25, ]


allcluster_table_motifFC <- rbind(table1_Motif, table2_Motif, table3_Motif, table4_Motif, table5_Motif, table6_Motif, table7_Motif) 
motif_interest <- allcluster_table_motifFC$Motif2
motif_interest <- unique(motif_interest)

allcluster_tableFC <- rbind(table1, table2, table3, table4, table5, table6, table7, table8) 

allcluster_tableFC$time <- factor(allcluster_tableFC$time, levels = c("cluster3", "cluster1", "cluster2", "cluster6", "cluster4", "cluster7", "cluster5", "static"))
```
```{r}
#create annotation column with CG data
cg_data<- read_tsv("/Users/lindsey/Desktop/Hodges_Lab/ATAC-me NPCdiff/NPCDiff_ATACme/New_timepoints/data/motto_output.txt", col_names = c("motif_ID", "Motif")) %>% separate(col = motif_ID, into = c("Motif_ID", "TF_name"), sep = "( )") %>% mutate(cg_state = case_when(grepl("CG", Motif) ~ "2.0", 
          grepl("CR", Motif) ~ "1.5", grepl("CS", Motif) ~ "1.5", grepl("CK", Motif) ~ "1.5",
          grepl("YG", Motif) ~ "1.5", grepl("SG", Motif) ~ "1.5", grepl("MG", Motif) ~ "1.5", 
          grepl("YR", Motif) ~ "1.0", grepl("YS", Motif) ~ "1.0", grepl("YK", Motif) ~ "1.0",
          grepl("SS", Motif) ~ "1.0", grepl("SR", Motif) ~ "1.0", grepl("SK", Motif) ~ "1.0",
          grepl("MR", Motif) ~ "1.0", grepl("MS", Motif) ~ "1.0", grepl("MK", Motif) ~ "1.0",
          TRUE ~ "0.0")) %>% mutate(Motif2 = toupper(TF_name))

allcluster_tableA<- allcluster_tableFC %>% select(-log_pval) %>% pivot_wider(names_from = time, values_from = percentFold, values_fn = mean) %>% drop_na() %>% mutate(Motif2 = toupper(Motif2))

allcluster_table_wide_cg<- inner_join(cg_data, allcluster_tableA, by= "Motif2") %>% select(Motif2, cg_state, Family)

#create rowname vector for annotation columns
anno_names <- make.names(allcluster_table_wide_cg$Motif2, unique = TRUE)
allcluster_table_wide_cg<- allcluster_table_wide_cg %>% select(-Motif2)
allcluster_table_wide_cg$cg_state<- as.factor(allcluster_table_wide_cg$cg_state)
allcluster_table_wide_cg$Family<- as.factor(allcluster_table_wide_cg$Family)
rownames(allcluster_table_wide_cg) <- anno_names
allcluster_table_wide_cg<- as.data.frame(allcluster_table_wide_cg)

#create matrix for heatmap filtering by those that have CpG data for their motif
allcluster_table_wide_cg_mat<- inner_join(cg_data, allcluster_tableA, by= "Motif2") %>% select("Motif2", "Closing I"="cluster3", "Closing II"="cluster1", "Intermediate I"="cluster2", "Intermediate II"="cluster6", "Intermediate III"="cluster4",  "Opening I"="cluster7", "Opening II"="cluster5", "Static"="static")

#create rowname vector for matrix
names<- make.names(allcluster_table_wide_cg_mat$Motif2, unique = TRUE)
allcluster_table_wide_cg_mat<- allcluster_table_wide_cg_mat %>% select(-Motif2)
rownames(allcluster_table_wide_cg_mat) <- anno_names

allcluster_table_mat_var <- head(order(rowVars(as.matrix(allcluster_table_wide_cg_mat[1:7])), decreasing = TRUE), 75)
allcluster_table_wide_cg_mat_wn<- allcluster_table_wide_cg_mat %>% rownames_to_column()
var_df_wn<- allcluster_table_wide_cg_mat_wn[allcluster_table_mat_var,]
var_df<- var_df_wn %>% column_to_rownames(var = "rowname")        

#scaled heatmap of most variable FC, signficant motifs with family data
cluster_center_motif_heatmap_mostvar <- pheatmap(var_df, 
                                      scale = "row", cluster_cols = FALSE, 
                                      annotation_row = allcluster_table_wide_cg[allcluster_table_mat_var,], 
                                      annotation_colors = ann_colors, border_color = NA,
                                      cellwidth = 15, cellheight = 3, fontsize_row = 5, 
                                      main = "Most Variable Motifs")
ggsave(cluster_center_motif_heatmap_mostvar, file = "/Users/lindsey/Desktop/Hodges_Lab/ATAC-me NPCdiff/NPCDiff_ATACme/New_timepoints/Figures/cluster_center_motif_heatmap_mostvar_cpgstate.pdf", device= cairo_pdf, units = "in", height = 10, width = 10)
```
